version: '3'

services: 
    rubik-general:
        image: ccr.ccs.tencentyun.com/big-devil/general:${VERSION}
        container_name: rubik-general
        environment: 
            JAVA_OPTS: "-Denv=${ENV} -D${ENV}_meta=http://${APOLLO_META} -Dapp.id=general -server -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"
        ports: 
            - "8081:8080"
            - "12582:8000"
        network_mode: "bridge"